server:
  port: 8080

spring:
  ## QQ邮箱配置
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 343715674@qq.com #发送邮件的邮箱地址
    password: seegrbeysczucbdb #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 343715674@qq.com # 发送邮件的地址，和上面username一致
    #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  mvc:
    static-path-pattern: static/**
  freemarker:
    template-loader-path: classpath:templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .html
  devtools:
    restart:
      enabled: false
  application:
    name: car-rental
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:myDb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;USER=sa
    druid:
      initial-size: 10
      max-active: 200
      min-idle: 10
      max-wait: 60000 #获取连接等待超时的时间
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      validation-query: SELECT 'x'
      validation-query-timeout: 2000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000  #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  #连接在池中最小生存的时间，单位是毫秒
      filters: stat              #监控统计拦截的filters
  sql:
    init:
      schema-locations: classpath:sql/init.sql
      data-locations: classpath:sql/data.sql

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-unknown-column-behavior: WARNING
    call-setters-on-nulls: false
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
